const display = document.querySelector("#resdis h2");
let button=document.querySelector("button")
let curinput=""
const one=document.getElementById("1")
const two =document.getElementById("2")
const three =document.getElementById("3")
const four =document.getElementById("4")
const five =document.getElementById("5")
const six =document.getElementById("6")
const sev =document.getElementById("7")
const eight =document.getElementById("8")
const nine =document.getElementById("9")
const equal =document.getElementById("=")
const del =document.getElementById("<=")
const remove =document.getElementById("AC")
const zero =document.getElementById("=")
const mul =document.getElementById("*")
const div =document.getElementById("/")
const addd =document.getElementById("-")
const sub =document.getElementById("-")
const per =document.getElementById("%")

